language: node_js
node_js:
- 13

services:
- docker

# Prétester les installations
install:
- echo "nothing needs to be installed"

# Scripts à exécuter en guise de tests
before_script:
- echo "no tests"

script:

  - docker --version 
  - docker build -t udagram-api-feed ./udagram-api-feed  
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed ChihabFortas/udagram-api-feed:latest 
  - docker tag udagram-api-user ChihabFortas/udagram-api-user:latest
  - docker tag udagram-frontend ChihabFortas/udagram-frontend:latest
  - docker tag udagram-reverseproxy ChihabFortas/udagram-reverseproxy:latest
 
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ChihabFortas/udagram-api-feed:latest
  - docker push ChihabFortas/udagram-api-user:latest
  - docker push ChihabFortas/udagram-frontend:latest
  - docker push ChihabFortas/udagram-reverseproxy:latest