language: node_js
node_js:
- 13

services:
- docker

# Prétester les installations
install:
- echo "nothing needs to be installed"

# Scripts à exécuter en guise de tests
before_script:
- echo "no tests"

script:

  - docker --version 
  - docker build -t udagram-api-feed ./udagram-api-feed  
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy

  - docker tag udagram-api-feed samscoot007/udagram-api-feed:v1 
  - docker tag udagram-api-user samscoot007/udagram-api-user:v1
  - docker tag udagram-frontend samscoot007/udagram-frontend:v1
  - docker tag udagram-reverseproxy samscoot007/udagram-reverseproxy:v1
 
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push samscoot007/udagram-api-feed:v1
  - docker push samscoot007/udagram-api-user:v1
  - docker push samscoot007/udagram-frontend:v1
  - docker push samscoot007/udagram-reverseproxy:v1